### ISSUE TITLE
Wrong JRE with 7.4.1.

### ISSUE THREAD

**Issue by MariusGrunenberg** [aborroy/alfresco-dockerx-builder#10]
Hi, 

it seems like when using the Builder with 7.4.1 the Share-Enterprise image seems to use CentOs with JRE 11 as a base image. 

That's why when using it in a project, we get errors since Repo is on Rocky Linux JRE17 and the code also is compiled to 17.

**Comment by aborroy** [comment]
You don't need to use this project for Share-Enterprise, is provided in both AMD64 and ARM64 architectures by default.

**Comment by aborroy** [comment]
Hope this fix helps: https://github.com/aborroy/alfresco-dockerx-builder/commit/9dbc239525736ea172a1b085c4088b682ee6424a

**Comment by MariusGrunenberg** [comment]
Ah yes thanks, I somehow missed that. :)
