### ISSUE TITLE
Alfresco Search Service 1.4.3.4 - Invalid Java version 11.0.16.1

### ISSUE THREAD

**Issue by uvukasinovic** [aborroy/alfresco-dockerx-builder#11]
When the ASS image is built for ARM64, it will use Java 11.0.16.1.

If we start the ASS container, we will have the error:

```
solr6-1     | Invalid Java version 11.0.16.1
solr6-1 exited with code 251
```

I think that the root of the error is the image below, which you can find in the Dockerfile for a search image:
`FROM alfresco/alfresco-base-java:jre11-rockylinux8-202209261621`

You provided more information about this bug:

https://hub.alfresco.com/t5/alfresco-content-services-forum/solr-6-5-5-is-not-starting-invalid-java-version-11-0-14-1/td-p/311564

I found issue using the image:

> alfresco/alfresco-search-services:1.4.3.4

**Comment by aborroy** [comment]
I've fixed base Docker Image for Search.

Let me know if this works for you.

**Comment by uvukasinovic** [comment]
It works now. 

Great, thank you.
