### ISSUE TITLE
Add support for custom repository when tagging

### ISSUE THREAD

**Issue by loftux** [aborroy/alfresco-dockerx-builder#2]
In the script att support for a custom repository in the tagging

For example:

```
REPOSITORY=alfresco
docker buildx build . --load --platform linux/arm64 -t $REPOSITORY/alfresco-content-repository-community:$REPO_COM_VERSION
```

That way you can replace the REPOSITORY variable and build custom images, and not mix the up with the official ones.

**Comment by aborroy** [comment]
Thanks for your contribution!
