### ISSUE TITLE
AGS Support

### ISSUE THREAD

**Issue by aborroy** [aborroy/alfresco-dockerx-builder#7]
Is there an AGS image that includes this fix?

_Originally posted by @michaeljmuller in https://github.com/aborroy/alfresco-dockerx-builder/issues/6#issuecomment-1433383233_

**Comment by aborroy** [comment]
@michaeljmuller This commit adds support for AGS.

Let me know if that works for you.

**Comment by michaeljmuller** [comment]
Thanks Angel!  I'll try it out later today or this weekend.
