### ISSUE TITLE
transform 2.4.0 fails and there's no target to build the "control center"

### ISSUE THREAD

**Issue by michaeljmuller** [aborroy/alfresco-dockerx-builder#9]
I was trying to build a 7.2 stack, but when I tried to use the buildx script to build transform 2.4.0 (trying to conform with the supported platforms doc) I got a 404.  I tried 2.4, 2.0, and 2.0.0 as well; no joy.  

So I decided to spin up a 7.4 stack, but that requires the "control center" which is apparently the new name for the "admin app" and buildx doesn't seem to have a target for that.

I'll see if I can cut/paste the admin app to make a control center target.  If I'm successful, I'll submit a PR.

**Comment by aborroy** [comment]
I've added support to build Transform Core AIO 2.x

To build the "control center", use the "aaa" code name:

```
$ ./buildx.sh aaa 7.12.0
```

**Comment by michaeljmuller** [comment]
Hi Angel, 

Thank you for the quick response, and sorry for my slow response to your response.  :)

I don't understand your suggestion for building the "control center".  In [7.4.N-docker-compose.yml](https://github.com/Alfresco/acs-deployment/blob/be3109fc945c9817c08073407f80b31de080c08e/docker-compose/7.4.N-docker-compose.yml#L160), docker creates a service based on the `alfresco-control-center:8.2.0 ` image.  

If I do `./buildx.sh aaa 8.2.0`, I get a "not found" error.  When I do `./buildx.sh aaa 7.12.0`, it builds an `alfresco-admin-app` image that won't be found by the 7.4.N docker compose.

I was going to proceed by copy/pasting the `aaa` code to create a `control-center` target.

**Comment by michaeljmuller** [comment]
Also, this is *not* urgent; we're not using the control center anyway and I can just comment the service out from my docker file for my immediate needs.

**Comment by aborroy** [comment]
Sorry, it was my mistake. I've included `control-center` building with the right Docker Image tag.

Try building it using a command similar to this one:

```
./buildx.sh control-center 8.2.0
```
